repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15  # 请根据需要更新到最新版本
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
